name: 'log-n-load-dev'

services:
  api:
    image: api
    build:
      context: api
      dockerfile: ./Dockerfile
      target: development      
    volumes:
      - ./api:/home/node/api
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "/home/node/api/node_modules/.bin/nest", "start", "--debug 0.0.0.0:9229", "--watch"]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 20s
  load:
    image: load
    build:
      context: load
      dockerfile: ./Dockerfile
      target: base      
      args:
        LOAD_TARGET: ${LOAD_TARGET:-http://api:3000}
        LOAD_ARRIVAL_RATE: ${LOAD_ARRIVAL_RATE:-10}
        LOAD_DURATION: ${LOAD_DURATION:-30}
    depends_on:
      api:
        condition: service_healthy
    command: ["run", "expect-200.yaml"]
